import { useMemo, useState } from "react";
import { format } from "date-fns";
import { ChevronLeft, Copy, Lock, ShieldAlert, Strikethrough } from "lucide-react";
import { useApp } from "@/state/AppContext";
import { cn } from "@/lib/utils";
import type { Notification } from "@/types/incident";

const DRAFT_DISCLAIMER =
  "This draft is generated by the system and must be reviewed, edited, and released by Legal Counsel before any external dispatch.";

const LegalDraftReview = () => {
  const { notifications, updateNotification, addAudit, user, incidents } = useApp();
  const [openId, setOpenId] = useState<string | null>(null);

  const drafts = useMemo(
    () =>
      notifications
        .filter((n) => n.status === "Draft")
        .sort((a, b) => +new Date(b.date) - +new Date(a.date)),
    [notifications],
  );

  const open = openId ? notifications.find((n) => n.id === openId) : null;

  if (open) {
    return (
      <DraftEditor
        draft={open}
        onBack={() => setOpenId(null)}
        onChange={(patch) => updateNotification(open.id, patch)}
        onRelease={() => {
          const ts = new Date().toISOString();
          updateNotification(open.id, {
            releasedByLegal: true,
            releasedAt: ts,
            releasedBy: user?.name ?? "Legal Counsel",
          });
          addAudit({
            incidentId: open.incidentId,
            actor: "Legal Counsel",
            action: `Draft legally released: ${open.subject}`,
          });
          setOpenId(null);
        }}
        onTogglePrivilege={() => {
          const newVal = !open.privileged;
          updateNotification(open.id, {
            privileged: newVal,
            privilegedBy: newVal ? user?.name ?? "Legal Counsel" : undefined,
            privilegedAt: newVal ? new Date().toISOString() : undefined,
          });
          if (newVal) {
            addAudit({
              incidentId: open.incidentId,
              actor: "Legal Counsel",
              action: `Privilege tag applied: ${open.subject}`,
            });
          }
        }}
        sourceFacts={incidents.find((i) => i.id === open.incidentId)}
      />
    );
  }

  return (
    <div className="px-10 py-10 max-w-[1200px] mx-auto animate-fade-in">
      <h1 className="font-serif text-[36px] leading-tight">Draft Review</h1>
      <p className="text-sm text-muted-foreground mt-2">
        Auto-generated notification drafts awaiting Legal Counsel review and release.
      </p>

      <div className="mt-4 text-[11px] text-warning bg-warning/5 border border-warning/20 rounded-sm px-3 py-2">
        {DRAFT_DISCLAIMER}
      </div>

      <div className="mt-6 space-y-3">
        {drafts.map((n) => (
          <button
            key={n.id}
            onClick={() => setOpenId(n.id)}
            className="w-full text-left bg-card border border-border shadow-card rounded-sm p-5 hover:bg-accent transition-colors"
          >
            <div className="grid grid-cols-1 md:grid-cols-[120px_140px_1fr_180px] gap-4 items-center">
              <span className="text-[10px] uppercase tracking-[0.18em] text-muted-foreground">
                {n.type}
              </span>
              <span className="text-xs font-mono text-muted-foreground">#{n.incidentId}</span>
              <span className="text-sm font-serif truncate">{n.subject}</span>
              <span
                className={cn(
                  "text-[10px] uppercase tracking-[0.18em] border rounded-sm px-2 py-1 w-fit",
                  n.releasedByLegal
                    ? "border-success/40 text-success bg-success/5"
                    : "border-border text-muted-foreground",
                )}
              >
                {n.releasedByLegal ? "Legally Released" : "Pending Legal Review"}
              </span>
            </div>
            {n.privileged && (
              <div className="mt-2 inline-flex items-center gap-1.5 text-[10px] uppercase tracking-[0.16em] text-destructive">
                <Lock className="w-3 h-3" /> privileged
              </div>
            )}
          </button>
        ))}
        {drafts.length === 0 && (
          <div className="py-16 text-center text-sm text-muted-foreground">
            No drafts awaiting review.
          </div>
        )}
      </div>
    </div>
  );
};

interface DraftEditorProps {
  draft: Notification;
  onBack: () => void;
  onChange: (patch: Partial<Notification>) => void;
  onRelease: () => void;
  onTogglePrivilege: () => void;
  sourceFacts?: { id: string; whatHappened: string; dataTypes: string[]; countries: string[] };
}

function DraftEditor({
  draft,
  onBack,
  onChange,
  onRelease,
  onTogglePrivilege,
  sourceFacts,
}: DraftEditorProps) {
  const [body, setBody] = useState(draft.body);
  const [subject, setSubject] = useState(draft.subject);

  function applyRedaction() {
    // Wrap the current selection in {{redact:...}} markers
    const ta = document.getElementById("draft-body") as HTMLTextAreaElement | null;
    if (!ta) return;
    const start = ta.selectionStart;
    const end = ta.selectionEnd;
    if (start === end) return;
    const before = body.slice(0, start);
    const sel = body.slice(start, end);
    const after = body.slice(end);
    const next = `${before}~~${sel}~~${after}`;
    setBody(next);
    onChange({ body: next });
  }

  return (
    <div className="px-10 py-10 max-w-[1400px] mx-auto animate-fade-in">
      <button
        onClick={onBack}
        className="inline-flex items-center gap-1 text-[11px] uppercase tracking-[0.18em] text-muted-foreground hover:text-foreground"
      >
        <ChevronLeft className="w-3 h-3" /> Back to drafts
      </button>

      <div className="mt-3 flex items-start justify-between flex-wrap gap-4">
        <div>
          <h1 className="font-serif text-[28px] leading-tight">{draft.subject}</h1>
          <div className="mt-1 text-[11px] text-muted-foreground">
            Type: {draft.type} · Incident #{draft.incidentId}
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={onTogglePrivilege}
            className={cn(
              "inline-flex items-center gap-2 border rounded-sm px-3 py-2 text-[11px] uppercase tracking-[0.16em] transition-colors",
              draft.privileged
                ? "border-destructive text-destructive bg-destructive/5"
                : "border-border hover:bg-accent",
            )}
          >
            <ShieldAlert className="w-3 h-3" />
            {draft.privileged ? "Privileged" : "Tag as Privileged"}
          </button>
          <button
            onClick={onRelease}
            disabled={draft.releasedByLegal}
            className="bg-primary text-primary-foreground px-4 py-2 text-[11px] uppercase tracking-[0.16em] rounded-sm hover:bg-primary/90 transition-colors disabled:opacity-50"
          >
            {draft.releasedByLegal ? "Released" : "Release Draft →"}
          </button>
        </div>
      </div>

      <div className="mt-3 text-[11px] text-warning bg-warning/5 border border-warning/20 rounded-sm px-3 py-2">
        {DRAFT_DISCLAIMER}
      </div>

      {draft.releasedByLegal && (
        <div className="mt-3 text-[11px] text-success bg-success/5 border border-success/20 rounded-sm px-3 py-2">
          Released by {draft.releasedBy}{" "}
          {draft.releasedAt && `on ${format(new Date(draft.releasedAt), "d LLL yyyy, HH:mm")}`} —
          awaiting Executive Management approval.
        </div>
      )}

      <div className="mt-6 grid grid-cols-1 lg:grid-cols-[1fr_320px] gap-6">
        {/* Editor */}
        <div className="bg-card border border-border shadow-card rounded-sm">
          <div className="px-5 py-3 border-b border-border flex items-center gap-2">
            <button
              onClick={applyRedaction}
              className="inline-flex items-center gap-1.5 text-[11px] uppercase tracking-[0.16em] border border-border rounded-sm px-2 py-1 hover:bg-accent transition-colors"
              title="Redact selected text"
            >
              <Strikethrough className="w-3 h-3" /> Redact selection
            </button>
            <button
              onClick={() => navigator.clipboard.writeText(body)}
              className="inline-flex items-center gap-1.5 text-[11px] uppercase tracking-[0.16em] border border-border rounded-sm px-2 py-1 hover:bg-accent transition-colors"
            >
              <Copy className="w-3 h-3" /> Copy
            </button>
            <span className="ml-auto text-[10px] uppercase tracking-[0.18em] text-muted-foreground">
              Wrap with ~~text~~ to redact
            </span>
          </div>
          <div className="p-5 space-y-4">
            <div>
              <div className="text-[10px] uppercase tracking-[0.18em] text-muted-foreground mb-1.5">
                Subject
              </div>
              <input
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
                onBlur={() => onChange({ subject })}
                className="w-full bg-background border border-border rounded-sm px-3 py-2 text-sm outline-none focus:border-primary"
              />
            </div>
            <div>
              <div className="text-[10px] uppercase tracking-[0.18em] text-muted-foreground mb-1.5">
                Body
              </div>
              <textarea
                id="draft-body"
                value={body}
                onChange={(e) => setBody(e.target.value)}
                onBlur={() => onChange({ body })}
                rows={18}
                className="w-full bg-background border border-border rounded-sm px-3 py-3 text-sm font-mono leading-relaxed outline-none focus:border-primary resize-y"
              />
            </div>
          </div>
        </div>

        {/* Source references */}
        <div className="bg-card border border-border shadow-card rounded-sm">
          <div className="px-5 py-3 border-b border-border">
            <h3 className="font-serif text-[16px]">Source references</h3>
            <div className="text-[10px] uppercase tracking-[0.18em] text-muted-foreground mt-0.5">
              Facts and articles backing this draft
            </div>
          </div>
          <div className="p-5 space-y-3 text-sm">
            <RefBlock title="Statutory">
              {draft.type === "Authority" && "GDPR Art. 33 — notification within 72h."}
              {draft.type === "Individual" && "GDPR Art. 34 — communication where high risk."}
              {draft.type === "Internal" && "Internal record per GDPR Art. 33(5)."}
            </RefBlock>
            {sourceFacts && (
              <>
                <RefBlock title="Incident facts">
                  {sourceFacts.whatHappened || "—"}
                </RefBlock>
                <RefBlock title="Data types">
                  {sourceFacts.dataTypes.join(", ") || "—"}
                </RefBlock>
                <RefBlock title="Countries">
                  {sourceFacts.countries.join(", ") || "—"}
                </RefBlock>
              </>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

function RefBlock({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <div className="text-[10px] uppercase tracking-[0.18em] text-muted-foreground mb-1">
        {title}
      </div>
      <div className="text-sm leading-relaxed">{children}</div>
    </div>
  );
}

export default LegalDraftReview;
